import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.sass'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Link href='/tenzies'>Tenzies</Link>
      </div>
      <div>
        <Link href='/quizz'>Quizz</Link>
      </div>
      <div>
        <Link href='/firsttohundred'>First to Hundred</Link>
      </div>

    </div>
  )
}
